package com.seraphim.yxsg.ui.page

import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.padding
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Surface
import androidx.compose.runtime.Composable
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.ui.Modifier
import androidx.navigation.NavHostController
import com.ramcosta.composedestinations.DestinationsNavHost
import com.ramcosta.composedestinations.generated.NavGraphs
import com.ramcosta.composedestinations.utils.rememberDestinationsNavigator
import com.seraphim.yxsg.ui.LocalDestinationsNavigator

@Composable
fun MainPage(navController: NavHostController) {
    val navigator = navController.rememberDestinationsNavigator()
    CompositionLocalProvider(LocalDestinationsNavigator provides navigator) {
        Scaffold(
            modifier = Modifier.fillMaxSize(),
        ) { innerPadding ->
            Surface {
                DestinationsNavHost(
                    navController = navController,
                    navGraph = NavGraphs.root, // Automatically generated by Compose Destinations
                    modifier = Modifier.padding(bottom = innerPadding.calculateBottomPadding()),
                    start = NavGraphs.root.defaultStartDirection,
                )
            }
        }
    }
}